#!/usr/bin/env python3

import subprocess
import sys

if __name__ == '__main__':
    # Run the training script with all command line arguments
    subprocess.check_call([sys.executable, 'train.py'] + sys.argv[1:])
